name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest

    environment:
      name: preview-pr-${{ github.event.number }}
      url: https://pqb.org.pl/preview/pr-${{ github.event.number }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          BASE_PATH: /preview/pr-${{ github.event.number }}
      - if: github.event.action != 'closed'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          target-folder: preview/pr-${{ github.event.number }}
          clean: false
      - if: github.event.action == 'closed'
        run: mkdir empty-dir
      - if: github.event.action == 'closed'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: empty-dir
          target-folder: preview/pr-${{ github.event.number }}
          clean: true
